"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['glinet-fav.png']
OPTIONS = {
    'iconfile':'./glinet.icns',
    'argv_emulation': False,
    'plist': {
        'LSUIElement': True,
    },
    'packages': ['rumps', 'chardet'],
    'includes': ['rumps', 'chardet', 'ipython', 'passlib', 'requests', 'tabulate'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    requires=['py2app', 'rumps'],
)
